import { expect, test } from '@playwright/test';

test('wind controls support two, many and zero vectors; reverse/opposition and resets update the rendered field', async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('/');await expect(page.locator('#loading')).toBeHidden();
  await expect(page.getByRole('button', { name: 'Winds', exact: true })).toBeHidden();
  await page.emulateMedia({ reducedMotion: 'reduce' });
  for (let i = 0; i < 4; i++) await page.keyboard.press('PageDown');
  await page.getByRole('button', { name: 'Winds', exact: true }).click();
  const winds = () => page.evaluate(() => (window as any).__study.snapshot().grass.winds);
  const original = await winds();expect(original).toHaveLength(2);
  await page.locator('.wind-entry > summary').nth(0).click();
  await page.getByRole('group', { name: 'Wind 1', exact: true }).getByRole('button', { name: 'Reverse', exact: true }).click();
  const reversed = await winds();
  reversed[0].vector.forEach((value: number, axis: number) => expect(value).toBeCloseTo(-original[0].vector[axis], 6));
  await page.locator('.wind-entry > summary').nth(1).click();
  await page.getByRole('button', { name: 'Oppose first', exact: true }).click();
  const opposed = await winds();
  const [a, b] = opposed.map((wind: any) => wind.vector);
  expect((a[0] * b[0] + a[1] * b[1]) / (Math.hypot(...a) * Math.hypot(...b))).toBeCloseTo(-1, 6);
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: 'Add wind', exact: true }).click();
  expect(await winds()).toHaveLength(5);
  await page.getByRole('slider', { name: 'Wind 3 strength', exact: true }).focus();
  await page.keyboard.press('End');expect((await winds())[2].strength).toBe(2);
  await page.getByRole('button', { name: 'Close wind controls' }).click();
  for (let i = 0; i < 4; i++) await page.keyboard.press('PageDown');
  await expect(page.locator('#app')).toHaveAttribute('data-study', 'wind-vectors');
  await page.getByRole('button', { name: 'Winds', exact: true }).click();
  await expect(page.locator('#wind-panel')).toBeVisible();expect(await winds()).toHaveLength(5);
  const windy = await page.screenshot({ clip: { x: 90, y: 200, width: 400, height: 240 } });
  for (let i = 0; i < 5; i++) await page.getByRole('button', { name: 'Remove', exact: true }).first().click();
  expect(await winds()).toHaveLength(0);await expect(page.locator('#wind-count')).toHaveText('0 active vectors');
  const still = await page.screenshot({ clip: { x: 90, y: 200, width: 400, height: 240 } });
  expect(still.equals(windy)).toBe(false);
  await page.getByRole('button', { name: 'Reset winds', exact: true }).click();
  const reset = await winds();expect(reset).toHaveLength(2);
  reset.forEach((wind: any, i: number) => expect(wind.vector).toEqual(original[i].vector));
  await page.screenshot({ path: 'state/wind-vectors-08.png' });
  expect(errors).toEqual([]);
});


test('wind disclosures keep edits and identity through collapse, navigation, removal and reset', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/?s=8');await expect(page.locator('#loading')).toBeHidden();
  await page.getByRole('button', { name: 'Winds', exact: true }).click();
  const entries = page.locator('.wind-entry');
  const summary = (index: number) => entries.nth(index).locator(':scope > summary');
  const winds = () => page.evaluate(() => (window as any).__study.snapshot().grass.winds);
  const initial = await winds();
  await expect(entries).toHaveCount(2);
  await expect(entries.nth(0).locator('fieldset')).toBeHidden();
  await expect(entries.nth(1).locator('fieldset')).toBeHidden();
  await summary(0).focus();await page.keyboard.press('Enter');
  await expect(entries.nth(0)).toHaveAttribute('open', '');
  const strength = page.getByRole('slider', { name: 'Wind 1 strength', exact: true });
  await strength.focus();await page.keyboard.press('End');
  await expect(summary(0)).toContainText('2.00');
  await summary(0).focus();await page.keyboard.press('Space');
  await expect(strength).toBeHidden();
  expect((await winds())[0].strength).toBe(2);
  await page.getByRole('button', { name: 'Add vortex', exact: true }).click();
  await expect(entries.nth(2)).toHaveAttribute('open', '');
  await page.getByRole('button', { name: 'Place on ground', exact: true }).click();
  await expect(page.locator('#world')).toHaveClass(/placing-wind/);
  await summary(2).click();
  await expect(page.locator('#wind-placement')).toBeHidden();
  await expect(page.locator('#world')).not.toHaveClass(/placing-wind/);
  await summary(0).click();
  await page.getByRole('button', { name: 'Reverse', exact: true }).click();
  await expect(entries.nth(0)).toHaveAttribute('open', '');
  await expect(strength).toHaveValue('2');
  await expect(entries.nth(1)).not.toHaveAttribute('open', '');
  await page.getByRole('button', { name: 'Remove', exact: true }).click();
  expect((await winds())[0].id).toBe(initial[1].id);
  await expect(entries.nth(0)).not.toHaveAttribute('open', '');
  await expect(summary(0)).toBeFocused();
  await summary(1).click();
  await entries.nth(1).getByRole('combobox').selectOption('radial');
  await expect(summary(1)).toContainText('From a point');
  await expect(entries.nth(1)).toHaveAttribute('open', '');
  await page.getByRole('button', { name: 'Close wind controls' }).click();
  await page.keyboard.press('7');await page.keyboard.press('8');
  await page.getByRole('button', { name: 'Winds', exact: true }).click();
  await expect(entries.nth(0)).not.toHaveAttribute('open', '');
  await expect(entries.nth(1)).toHaveAttribute('open', '');
  await page.getByRole('button', { name: 'Reset winds', exact: true }).click();
  await expect(entries).toHaveCount(2);
  await expect(entries.nth(0)).not.toHaveAttribute('open', '');
  await expect(entries.nth(1)).not.toHaveAttribute('open', '');
  expect((await winds()).map(({ vector }: any) => vector)).toEqual(initial.map(({ vector }: any) => vector));
  await page.screenshot({ path: 'state/wind-collapsed-dark.png' });
  await page.emulateMedia({ colorScheme: 'light' });
  await page.screenshot({ path: 'state/wind-collapsed-light.png' });
});
